name: PIRT
version: "${version}"
main: dev.darkblade.pirt.platform.paper.PirtPlugin
api-version: "1.20"
author: DarkBlade
description: Players In Region Tracker
softdepend: [WorldGuard, PlaceholderAPI]
commands:
  pirt:
    description: Main command for PIRT
    permission: pirt.admin
    usage: /pirt help
